###2.Exploratory Analysis###

##2.1 bar charts of electricity generation by source##
library('ggplot2')
library('dplyr')
library('scales')

#calculate electricity generated by percentage of total generation#
m5=m3 #making sure that data (m3) is available in its original form

#first create function for total gen/cust
elec_perc=function(col) {
  round((sum(col) / sum(m5[,c(3:12)]))*100,1)
}

percent_by_source=apply(m5[,c(3:12)], 2,elec_perc) #store percentages
percent_by_source=data.frame(percent_by_source) #convert to df
library(data.table)
setDT(percent_by_source, keep.rownames = TRUE)[] #convert index to column
str(percent_by_source)

plot1=ggplot(data=percent_by_source,aes(x=rn,y=percent_by_source,fill=rn))+geom_bar(stat='identity')+xlab('Source')+
  ylab('% Total')+ggtitle('Electricity Generation in United States (2016)')+ylim(0,50)+
  theme(plot.title = element_text(hjust = 0.5))+theme(axis.text.x = element_blank());plot1


##2.2 generate usa heatmap of electricity generation (Alaska and Hawaii included)##
install.packages("devtools")
devtools::install_github("wmurphyrd/fiftystater")
library(fiftystater)

data("fifty_states") # this line is optional due to lazy data loading
renewables <- data.frame(state = tolower(rownames(re)), re) #plug in re dataset here

#map_id creates the aesthetic mapping to the state name column in your data#
p <- ggplot(renewables, aes(map_id = State)) + 
  # map points to the fifty_states shape data
  geom_map(aes(fill = PercentRenewables), map = fifty_states) + 
  expand_limits(x = fifty_states$long, y = fifty_states$lat) +
  coord_map() +
  scale_x_continuous(breaks = NULL) + 
  scale_y_continuous(breaks = NULL) +
  labs(x = "", y = "") +
  theme(legend.position = "bottom", 
        panel.background = element_blank());p


##2.3 boxplots##
m6=m4[,c(4:13)]
m6$other[m6$other<0]=0 #need get rid of negative values, since sqrt variables 
                       #only 3 negative values and they are small, so shouldnt impact visualization
m6[] <- lapply(m6,sqrt) #sqrt values in dataframe in order to make differences more clear in plot
m6=cbind(m4[,c(1,2,3)],m6) #append state, year, and affiliation to dataframe

aggregate(m6[,4:13],list(m6$Affiliation),mean) #numbers indicate large mean differences in coal, bio, and petrol
long_DF <- m6 %>% gather(Source, Generation, coal:wood) #reshape from wide to long in order to plot
plot2=ggplot(data=long_DF,aes(x=Source,y=Generation,fill=Affiliation))+geom_boxplot()+xlab('Electricity Generation by Source')+ylab('Generation per Customer (√MWH)')+ggtitle('Red States vs. Blue States (2016)')+  theme(plot.title = element_text(hjust = 0.5));plot2

##view correlation between variables##
m4.cor = cor(m4[,c(4:13)]);m4.cor
